import 'app_state.dart';

/// Returns localized string for [key] based on current AppState.language
class L {
  L._();

  static String t(String key) {
    final lang = AppState.language.value;
    return (_data[lang] ?? _data['uz']!)[key] ?? key;
  }

  static const _data = <String, Map<String, String>>{
    // ─── O'ZBEKCHA ─────────────────────────────────────────
    'uz': {
      // Umumiy
      'app_name': 'Quiz App',
      'continue_btn': 'Davom etish',
      'back': 'Orqaga',
      // Til tanlash
      'choose_language': 'Tilni tanlang',
      'language_hint': 'Iltimos, qulay tilni tanlang',
      // Login
      'login_title': 'Kirish',
      'login_subtitle': "Ma'lumotlaringizni kiriting",
      'name_label': 'F.I.Sh',
      'name_hint': 'Ismingizni kiriting',
      'id_label': 'ID raqam',
      'id_hint': 'ID raqamingizni kiriting',
      'fill_all': "Barcha maydonlarni to'ldiring",
      // Bosh sahifa
      'welcome': 'Xush kelibsiz,',
      'welcome_sub': 'Bugun yangi bilimlar olasiz!',
      'popular': 'Mashhur fanlar',
      'all': 'Barchasi',
      'start_test': 'Testni boshlash',
      'statistics': 'Statistika',
      'tests_taken': "O'tkazilgan testlar",
      'avg_score': "O'rtacha natija",
      'best_score': 'Eng yaxshi ball',
      // Fanlar
      'choose_subject': 'Fanlarni tanlang',
      'search_hint': 'Fan nomini qidiring...',
      'tests_count': 'ta test',
      // Quiz
      'question_of': 'Savol',
      'next_q': 'Keyingi savol',
      'finish': 'Yakunlash',
      // Natijalar
      'quiz_done': 'Ajoyib! Test yakunlandi!',
      'your_score': 'Sizning ballingiz',
      'msg_excellent': "A'lo natija! Davom eting!",
      'msg_good': "Yaxshi! Ko'proq mashq qiling!",
      'msg_try': "Harakat qiling! Keyingi safar yaxshiroq!",
      'correct': "To'g'ri javoblar",
      'wrong': "Noto'g'ri javoblar",
      'total_q': 'Jami savollar',
      'retry': 'Qayta ishlash',
      'go_home': 'Bosh sahifaga qaytish',
      // Statistika
      'stat_title': 'Statistika',
      'last_7': "So'nggi 7 test",
      'results_analysis': 'Natijalar tahlili',
      'recent_results': "So'nggi natijalar",
      // Profil
      'profile_title': 'Profil',
      'my_info': "Ma'lumotlarim",
      'name_field': "F.I.Sh",
      'id_field': 'ID raqam',
      'settings_title': 'Sozlamalar',
      'dark_mode': 'Dark Mode',
      'notifs': 'Bildirishnomalar',
      'lang_settings': 'Til sozlamalari',
      'about': 'Ilova haqida',
      'version': 'Versiya 1.0.0',
      'logout': 'Chiqish',
      'copyright': '© 2024 Quiz App. Barcha huquqlar himoyalangan.',
      // Drawer
      'drawer_home': 'Bosh sahifa',
      'drawer_subjects': 'Fanlar',
      'drawer_stats': 'Statistika',
      'drawer_profile': 'Profil',
      'drawer_about': 'Ilova haqida',
      'drawer_lang': 'Tilni o\'zgartirish',
      // About
      'about_title': 'Ilova haqida',
      'about_desc':
          'Quiz App – universitetga kiruvchilar uchun imtihonlarga tayyorlanish va bilimlarni mustahkamlash ilovasi.',
      'about_local': "Mahalliy ma'lumotlar",
      'about_local_sub': "Barcha ma'lumotlar qurilmangizda saqlanadi",
      'about_dev': 'Ishlab chiquvchi',
      'about_dev_sub': 'O\'rgimchilar jamoasi',
      'about_contact': "Bog'lanish",
      'about_contact_sub': 'quizapp@example.com',
      // Fan nomlari
      'math': 'Matematika',
      'coding': 'Dasturlash',
      'english': 'Ingliz tili',
      'history': 'Tarix',
      'physics': 'Fizika',
    },

    // ─── РУССКИЙ ────────────────────────────────────────────
    'ru': {
      'app_name': 'Quiz App',
      'continue_btn': 'Продолжить',
      'back': 'Назад',
      'choose_language': 'Выберите язык',
      'language_hint': 'Пожалуйста, выберите удобный язык',
      'login_title': 'Вход',
      'login_subtitle': 'Введите ваши данные',
      'name_label': 'Ф.И.О',
      'name_hint': 'Введите ваше имя',
      'id_label': 'ID номер',
      'id_hint': 'Введите ваш ID номер',
      'fill_all': 'Заполните все поля',
      'welcome': 'Добро пожаловать,',
      'welcome_sub': 'Сегодня получите новые знания!',
      'popular': 'Популярные предметы',
      'all': 'Все',
      'start_test': 'Начать тест',
      'statistics': 'Статистика',
      'tests_taken': 'Пройдено тестов',
      'avg_score': 'Средний балл',
      'best_score': 'Лучший балл',
      'choose_subject': 'Выберите предмет',
      'search_hint': 'Поиск предмета...',
      'tests_count': 'тестов',
      'question_of': 'Вопрос',
      'next_q': 'Следующий вопрос',
      'finish': 'Завершить',
      'quiz_done': 'Отлично! Тест завершён!',
      'your_score': 'Ваш результат',
      'msg_excellent': 'Отличный результат! Продолжайте!',
      'msg_good': 'Хорошо! Больше практикуйтесь!',
      'msg_try': 'Стараться! В следующий раз лучше!',
      'correct': 'Правильные ответы',
      'wrong': 'Неправильные ответы',
      'total_q': 'Всего вопросов',
      'retry': 'Повторить',
      'go_home': 'На главную',
      'stat_title': 'Статистика',
      'last_7': 'Последние 7 тестов',
      'results_analysis': 'Анализ результатов',
      'recent_results': 'Последние результаты',
      'profile_title': 'Профиль',
      'my_info': 'Мои данные',
      'name_field': 'Ф.И.О',
      'id_field': 'ID номер',
      'settings_title': 'Настройки',
      'dark_mode': 'Тёмная тема',
      'notifs': 'Уведомления',
      'lang_settings': 'Настройки языка',
      'about': 'О приложении',
      'version': 'Версия 1.0.0',
      'logout': 'Выйти',
      'copyright': '© 2024 Quiz App. Все права защищены.',
      'drawer_home': 'Главная',
      'drawer_subjects': 'Предметы',
      'drawer_stats': 'Статистика',
      'drawer_profile': 'Профиль',
      'drawer_about': 'О приложении',
      'drawer_lang': 'Сменить язык',
      'about_title': 'О приложении',
      'about_desc':
          'Quiz App – приложение для подготовки к экзаменам и закрепления знаний для поступающих в университет.',
      'about_local': 'Локальные данные',
      'about_local_sub': 'Все данные хранятся на вашем устройстве',
      'about_dev': 'Разработчик',
      'about_dev_sub': 'Команда разработчиков',
      'about_contact': 'Связаться',
      'about_contact_sub': 'quizapp@example.com',
      'math': 'Математика',
      'coding': 'Программирование',
      'english': 'Английский язык',
      'history': 'История',
      'physics': 'Физика',
    },

    // ─── ENGLISH ─────────────────────────────────────────────
    'en': {
      'app_name': 'Quiz App',
      'continue_btn': 'Continue',
      'back': 'Back',
      'choose_language': 'Choose Language',
      'language_hint': 'Please choose your preferred language',
      'login_title': 'Login',
      'login_subtitle': 'Enter your details',
      'name_label': 'Full Name',
      'name_hint': 'Enter your name',
      'id_label': 'ID Number',
      'id_hint': 'Enter your ID number',
      'fill_all': 'Please fill in all fields',
      'welcome': 'Welcome,',
      'welcome_sub': 'Learn something new today!',
      'popular': 'Popular Subjects',
      'all': 'All',
      'start_test': 'Start Test',
      'statistics': 'Statistics',
      'tests_taken': 'Tests Taken',
      'avg_score': 'Average Score',
      'best_score': 'Best Score',
      'choose_subject': 'Choose Subject',
      'search_hint': 'Search subject...',
      'tests_count': 'tests',
      'question_of': 'Question',
      'next_q': 'Next Question',
      'finish': 'Finish',
      'quiz_done': 'Great! Test Completed!',
      'your_score': 'Your Score',
      'msg_excellent': 'Excellent! Keep it up!',
      'msg_good': 'Good! Practice more!',
      'msg_try': 'Keep trying! Better next time!',
      'correct': 'Correct Answers',
      'wrong': 'Wrong Answers',
      'total_q': 'Total Questions',
      'retry': 'Try Again',
      'go_home': 'Go to Home',
      'stat_title': 'Statistics',
      'last_7': 'Last 7 Tests',
      'results_analysis': 'Results Analysis',
      'recent_results': 'Recent Results',
      'profile_title': 'Profile',
      'my_info': 'My Information',
      'name_field': 'Full Name',
      'id_field': 'ID Number',
      'settings_title': 'Settings',
      'dark_mode': 'Dark Mode',
      'notifs': 'Notifications',
      'lang_settings': 'Language Settings',
      'about': 'About App',
      'version': 'Version 1.0.0',
      'logout': 'Log Out',
      'copyright': '© 2024 Quiz App. All rights reserved.',
      'drawer_home': 'Home',
      'drawer_subjects': 'Subjects',
      'drawer_stats': 'Statistics',
      'drawer_profile': 'Profile',
      'drawer_about': 'About App',
      'drawer_lang': 'Change Language',
      'about_title': 'About App',
      'about_desc':
          'Quiz App – a study companion for university entrance exam preparation and knowledge reinforcement.',
      'about_local': 'Local Data',
      'about_local_sub': 'All data is stored on your device',
      'about_dev': 'Developer',
      'about_dev_sub': 'Development Team',
      'about_contact': 'Contact',
      'about_contact_sub': 'quizapp@example.com',
      'math': 'Mathematics',
      'coding': 'Programming',
      'english': 'English',
      'history': 'History',
      'physics': 'Physics',
    },
  };
}
